-- $Id$

drop index USER_NAME_INDEX;

drop table USERS;

--==============================================================
-- Table: USERS
--==============================================================
create table USERS
(
   ID                   BIGINT                 not null generated by default as identity,
   USER_NAME            VARCHAR(20)            not null,
   PASSWORD             VARCHAR(20),
   constraint P_KEY_1 primary key (ID)
);

--==============================================================
-- Index: USER_NAME_INDEX
--==============================================================
create unique index USER_NAME_INDEX on USERS (
   USER_NAME            ASC
);